### PR TITLE
Add ability to use XPath queries from within the .yaml config

### PR DESCRIPTION
**Pull request by hellothisisMatt**
**This pull request adds the ability for a user to specify an XPath query directly in the config.yaml.**
The necessity for this functionality arose when we tried to extract information from the NCBI XML that was structured as follows:

```
<GBSeq_feature-table>
    <GBFeature>
        <GBFeature_key>source</GBFeature_key>
        <GBFeature_quals>
            <GBQualifier>
                <GBQualifier_name>organism</GBQualifier_name>
                <GBQualifier_value>my_name</GBQualifier_value>
            </GBQualifier>
        </GBFeature_quals>
    </GBFeature>
    <GBFeature>
        <GBFeature_key>gene</GBFeature_key>
        <GBFeature_quals>
            <GBQualifier>
                <GBQualifier_name>gene</GBQualifier_name>
                <GBQualifier_value>my_gene_here</GBQualifier_value>
            </GBQualifier>
        </GBFeature_quals>
    </GBFeature>
</GBSeq_feature-table>
```
We would like to get the value of GBQualifier_name == organism within the GBFeature_key == source node. One of the easiest ways is to write XPath queries with conditionals to specify the exact node that is desired. 

**Changes**
1. Add `adv_xml_search` which takes an XPath query separated with commas, or raw XPath command without `//` prepended. This method performs a search using the XPath query given on the XML tree and returns matching element values.

2. Add logic to check if column_payload's first element is "XPATH". If it is, perform `adv_xml_search` otherwise continue with existing logic.

3. Add documentation to `README_config.md` on how to specify an XPATH command as the query to access a node's value.

### CODE REVIEW

**Comment by ktmeaton** [comment]
Thank you so much for writing this, I was just wrestling with almost the exact same problem yesterday and had no idea how to tackle it!

I'm going to get started on writing some test suites + CI deployment. Hopefully this should be pushed to the master branch next week :)

**Comment by hellothisisMatt** [comment]
No worries! Thanks for writing a wicked useful tool :) :+1:

**Comment by Takadonet** [comment]
@ktmeaton that is awesome! @hellothisisMatt  and myself are already using this functionality in our local conda environment of NCBImeta. Cannot wait for official release.

**Comment by ktmeaton** [comment]
Hi @hellothisisMatt and @Takadonet, I was wondering about your opinion on making the config.yaml just take fully formatted XPath queries, which might look like:
```
- GBOrganismName: XPATH, .//GBSeq_feature-table/GBFeature[GBFeature_key/text() = 'source']/GBFeature_quals/GBQualifier[GBQualifier_name/text() = 'organism']/GBQualifier_value
- NucleotideBioSampleAccession: XPATH, //GBXref[GBXref_dbname/text() = 'BioSample']/GBXref_id
```

My thinking is that there are many different ways you can construct an XPath query to achieve your search goal. And if someone already wants the advanced functionality of XPath, they might benefit from What You See Is What You Get (ie. little to no reformatting in internal functions)

For example, with your document:
```
<GBSeq_feature-table>
    <GBFeature>
        <GBFeature_key>source</GBFeature_key>
        <GBFeature_quals>
            <GBQualifier>
                <GBQualifier_name>organism</GBQualifier_name>
                <GBQualifier_value>my_name</GBQualifier_value>
            </GBQualifier>
        </GBFeature_quals>
    </GBFeature>
    <GBFeature>
        <GBFeature_key>gene</GBFeature_key>
        <GBFeature_quals>
            <GBQualifier>
                <GBQualifier_name>gene</GBQualifier_name>
                <GBQualifier_value>my_gene_here</GBQualifier_value>
            </GBQualifier>
        </GBFeature_quals>
    </GBFeature>
</GBSeq_feature-table>
```

In your query, we can search using a precise path starting at the current node (.//query)
```
.//GBSeq_feature-table/GBFeature[GBFeature_key/text() = 'source']/GBFeature_quals/GBQualifier[GBQualifier_name/text() = 'organism']/GBQualifier_value"
```
Or another approach might involve not starting at the current node, because the conditionals are precise enough (//query)
```
//GBQualifier[GBQualifier_name/text() = 'organism']/GBQualifier_value"
```

However, this is different from what you originally implemented with the comma-separated nodes and conditionals. What do you think?

**Comment by hellothisisMatt** [comment]
Hey, I think that's a great idea!
In this pull request, there is functionality to take either a friendly XPath separated by commas and functionality to take entire raw XPaths as well. 

Therefore we can have queries like this:
```
foo : XPATH, GBSeq_feature-table, GBFeature[GBFeature_key/text() = "source"], GBFeature_quals, GBQualifier[GBQualifier_name/text() = "organism"], GBQualifier_value
bar : XPATH, GBSeq_feature-table/GBFeature[GBFeature_key/text() = "source"]/GBFeature_quals/GBQualifier[GBQualifier_name/text() = "mol_type"]/GBQualifier_value
```


An issue with the implementation I've done is that it requires the XPath command without // prepended. A solution to this could be removing the comma separated XPath implementation and instead only evaluate the entire query as a proper XPath string. 

If that works for you, I can make that change ASAP!

**Comment by ktmeaton** [comment]
I've created a PR with some of the unit tests, and edits I've made over at https://github.com/hellothisisMatt/NCBImeta/pull/1. They're only suggestions though, so if you find what I've proposed to not be a good fit, let me know!

**Comment by hellothisisMatt** [comment]
I've merged your PR on my forked copy. Feel free to push any updates to this branch if changes are needed.

**Comment by ktmeaton** [comment]
Thank you! I think the last thing to implement is the [null checking as you suggested](https://github.com/hellothisisMatt/NCBImeta/pull/1#discussion_r389104626) to catch:
```
MyColumnName : XPATH
```
Which is a great idea! I can add that and then try to queue this up for release in the next few days.

**Comment by ktmeaton** [comment]
I think Codecov is slightly upset because I had skipped Continuous Integration + uploading a Codecov report right before this PR was created. But I'm satisfied that most things we know could go wrong have been accounted for!

**Comment by hellothisisMatt** [comment]
Awesome work, thanks for merging this!

**Pull request merged**
